### ISSUE TITLE
Removing things not part of core emulator 

### ISSUE THREAD

**Issue by bayedieng** [ultimaweapon/obliteration#55]
Currently Vulkan is cited as a requirement for the project when it is not necessary for building and running it. There's also kyty and uplift repo which are being used as reference; it would be more fitting for them to be git submodules as they are also not part of the core emulator.

**Comment by ultimaweapon** [comment]
Agree with Vulkan since it is still unclear how we are going to emulate the GPU. For Kyty and Uplift actually I keep it in the repository because I need to keep track which part of it that I already understand. Now we have more people joining so I agree that we should remove it completely.

For Kyty and Uplift I'll remove it so we will not accidentally remove my local notes. For Vulkan you can remove it if you are interested in this task :)
